// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Credential is an email+password pair found in messages.
 */
export class Credential {
    "email": string;
    "password": string;

    /**
     * header|body
     */
    "source": string;

    /** Creates a new Credential instance. */
    constructor($$source: Partial<Credential> = {}) {
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Credential instance from a string or object.
     */
    static createFrom($$source: any = {}): Credential {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Credential($$parsedSource as Partial<Credential>);
    }
}
