// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as imapextract$0 from "../imapextract/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inboxcheck$0 from "../inboxcheck/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worker$0 from "../worker/models.js";

export class AnalyzeAllResult {
    "total": number;
    "ok": number;
    "failed": number;
    "batches": number;

    /**
     * smtp id → summary
     */
    "results": { [_ in string]?: inboxcheck$0.PlacementSummary };

    /**
     * smtp id → error
     */
    "errors": { [_ in string]?: string };

    /** Creates a new AnalyzeAllResult instance. */
    constructor($$source: Partial<AnalyzeAllResult> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("ok" in $$source)) {
            this["ok"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("batches" in $$source)) {
            this["batches"] = 0;
        }
        if (!("results" in $$source)) {
            this["results"] = {};
        }
        if (!("errors" in $$source)) {
            this["errors"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeAllResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeAllResult {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField4_0($$parsedSource["results"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField5_0($$parsedSource["errors"]);
        }
        return new AnalyzeAllResult($$parsedSource as Partial<AnalyzeAllResult>);
    }
}

/**
 * DeployServerResult is returned per-server after SOCKS deploy.
 */
export class DeployServerResult {
    "id": number;
    "host": string;
    "ok": boolean;
    "port": number;
    "message": string;
    "error"?: string;

    /** Creates a new DeployServerResult instance. */
    constructor($$source: Partial<DeployServerResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployServerResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DeployServerResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeployServerResult($$parsedSource as Partial<DeployServerResult>);
    }
}

/**
 * ExtractMailboxResult is IMAP scrape + optional import counts.
 */
export class ExtractMailboxResult {
    "imap_host": string;
    "imap_port": number;
    "imap_encryption": string;
    "messages_scanned": number;

    /**
     * preview (full list is on disk + email queue)
     */
    "contacts": string[];
    "credentials": imapextract$0.Credential[];
    "contacts_file": string;
    "creds_file": string;
    "contact_count": number;
    "imported_emails": number;
    "skipped_emails": number;
    "imported_smtps": number;
    "updated_smtps": number;

    /** Creates a new ExtractMailboxResult instance. */
    constructor($$source: Partial<ExtractMailboxResult> = {}) {
        if (!("imap_host" in $$source)) {
            this["imap_host"] = "";
        }
        if (!("imap_port" in $$source)) {
            this["imap_port"] = 0;
        }
        if (!("imap_encryption" in $$source)) {
            this["imap_encryption"] = "";
        }
        if (!("messages_scanned" in $$source)) {
            this["messages_scanned"] = 0;
        }
        if (!("contacts" in $$source)) {
            this["contacts"] = [];
        }
        if (!("credentials" in $$source)) {
            this["credentials"] = [];
        }
        if (!("contacts_file" in $$source)) {
            this["contacts_file"] = "";
        }
        if (!("creds_file" in $$source)) {
            this["creds_file"] = "";
        }
        if (!("contact_count" in $$source)) {
            this["contact_count"] = 0;
        }
        if (!("imported_emails" in $$source)) {
            this["imported_emails"] = 0;
        }
        if (!("skipped_emails" in $$source)) {
            this["skipped_emails"] = 0;
        }
        if (!("imported_smtps" in $$source)) {
            this["imported_smtps"] = 0;
        }
        if (!("updated_smtps" in $$source)) {
            this["updated_smtps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractMailboxResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtractMailboxResult {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contacts" in $$parsedSource) {
            $$parsedSource["contacts"] = $$createField4_0($$parsedSource["contacts"]);
        }
        if ("credentials" in $$parsedSource) {
            $$parsedSource["credentials"] = $$createField5_0($$parsedSource["credentials"]);
        }
        return new ExtractMailboxResult($$parsedSource as Partial<ExtractMailboxResult>);
    }
}

export class ImportResult {
    "inserted": number;
    "updated": number;

    /**
     * duplicates already in DB (or input dupes when not validating)
     */
    "skipped": number;

    /**
     * failed validation (syntax/DNS)
     */
    "invalid": number;
    "total": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("inserted" in $$source)) {
            this["inserted"] = 0;
        }
        if (!("updated" in $$source)) {
            this["updated"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("invalid" in $$source)) {
            this["invalid"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

export class Stats {
    "status": store$0.StatusCounts;
    "campaign": store$0.Campaign;
    "top_errors": string[];
    "rate": number;
    "rate_history": worker$0.RatePoint[];
    "smtp_stats": store$0.SMTPStat[];
    "running": boolean;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new store$0.StatusCounts());
        }
        if (!("campaign" in $$source)) {
            this["campaign"] = (new store$0.Campaign());
        }
        if (!("top_errors" in $$source)) {
            this["top_errors"] = [];
        }
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }
        if (!("rate_history" in $$source)) {
            this["rate_history"] = [];
        }
        if (!("smtp_stats" in $$source)) {
            this["smtp_stats"] = [];
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType3;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        if ("campaign" in $$parsedSource) {
            $$parsedSource["campaign"] = $$createField1_0($$parsedSource["campaign"]);
        }
        if ("top_errors" in $$parsedSource) {
            $$parsedSource["top_errors"] = $$createField2_0($$parsedSource["top_errors"]);
        }
        if ("rate_history" in $$parsedSource) {
            $$parsedSource["rate_history"] = $$createField4_0($$parsedSource["rate_history"]);
        }
        if ("smtp_stats" in $$parsedSource) {
            $$parsedSource["smtp_stats"] = $$createField5_0($$parsedSource["smtp_stats"]);
        }
        return new Stats($$parsedSource as Partial<Stats>);
    }
}

// Private type creation functions
const $$createType0 = inboxcheck$0.PlacementSummary.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = imapextract$0.Credential.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = store$0.StatusCounts.createFrom;
const $$createType7 = store$0.Campaign.createFrom;
const $$createType8 = worker$0.RatePoint.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = store$0.SMTPStat.createFrom;
const $$createType11 = $Create.Array($$createType10);
