// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PlacementDetail {
    "email": string;
    "provider": string;

    /**
     * inbox | spam | other | missing | error
     */
    "placement": string;
    "error"?: string;

    /** Creates a new PlacementDetail instance. */
    constructor($$source: Partial<PlacementDetail> = {}) {
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("placement" in $$source)) {
            this["placement"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlacementDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): PlacementDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlacementDetail($$parsedSource as Partial<PlacementDetail>);
    }
}

export class PlacementSummary {
    "score": number;
    "inbox": number;
    "spam": number;
    "other": number;
    "missing": number;
    "total": number;
    "inbox_rate": number;
    "label": string;
    "summary": string;
    "public_id": string;
    "report_url"?: string;
    "details": PlacementDetail[];

    /** Creates a new PlacementSummary instance. */
    constructor($$source: Partial<PlacementSummary> = {}) {
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("inbox" in $$source)) {
            this["inbox"] = 0;
        }
        if (!("spam" in $$source)) {
            this["spam"] = 0;
        }
        if (!("other" in $$source)) {
            this["other"] = 0;
        }
        if (!("missing" in $$source)) {
            this["missing"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("inbox_rate" in $$source)) {
            this["inbox_rate"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("public_id" in $$source)) {
            this["public_id"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlacementSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PlacementSummary {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField11_0($$parsedSource["details"]);
        }
        return new PlacementSummary($$parsedSource as Partial<PlacementSummary>);
    }
}

/**
 * Seed is kept for YAML/bindings backward compatibility; unused by MailReach flow.
 */
export class Seed {
    "provider": string;
    "email": string;
    "password": string;

    /** Creates a new Seed instance. */
    constructor($$source: Partial<Seed> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Seed instance from a string or object.
     */
    static createFrom($$source: any = {}): Seed {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Seed($$parsedSource as Partial<Seed>);
    }
}

// Private type creation functions
const $$createType0 = PlacementDetail.createFrom;
const $$createType1 = $Create.Array($$createType0);
