// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Campaign {
    "id": number;
    "state": string;
    "html": string;
    "from_name": string;
    "started_at": string;
    "updated_at": string;

    /** Creates a new Campaign instance. */
    constructor($$source: Partial<Campaign> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("html" in $$source)) {
            this["html"] = "";
        }
        if (!("from_name" in $$source)) {
            this["from_name"] = "";
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Campaign instance from a string or object.
     */
    static createFrom($$source: any = {}): Campaign {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Campaign($$parsedSource as Partial<Campaign>);
    }
}

export class Email {
    "id": number;
    "address": string;
    "status": string;
    "attempts": number;
    "smtp_id"?: number | null;
    "error": string;
    "subject": string;
    "link": string;
    "updated_at": string;

    /** Creates a new Email instance. */
    constructor($$source: Partial<Email> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("attempts" in $$source)) {
            this["attempts"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Email instance from a string or object.
     */
    static createFrom($$source: any = {}): Email {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Email($$parsedSource as Partial<Email>);
    }
}

/**
 * EmailPage is a paginated slice of emails plus total matching rows.
 */
export class EmailPage {
    "items": Email[];
    "total": number;
    "limit": number;
    "offset": number;

    /** Creates a new EmailPage instance. */
    constructor($$source: Partial<EmailPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmailPage instance from a string or object.
     */
    static createFrom($$source: any = {}): EmailPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new EmailPage($$parsedSource as Partial<EmailPage>);
    }
}

export class SMTP {
    "id": number;
    "domain": string;
    "account_label": string;
    "host": string;
    "port": number;
    "encryption": string;
    "from_addr": string;
    "user": string;
    "password"?: string;
    "status": string;
    "fail_count": number;
    "last_error": string;
    "sent_count": number;
    "inbox_score": number;
    "inbox_rate": number;
    "inbox_label": string;
    "spam_test_id": string;
    "spam_checked_at": string;
    "spam_summary": string;

    /** Creates a new SMTP instance. */
    constructor($$source: Partial<SMTP> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("account_label" in $$source)) {
            this["account_label"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("encryption" in $$source)) {
            this["encryption"] = "";
        }
        if (!("from_addr" in $$source)) {
            this["from_addr"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("fail_count" in $$source)) {
            this["fail_count"] = 0;
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }
        if (!("sent_count" in $$source)) {
            this["sent_count"] = 0;
        }
        if (!("inbox_score" in $$source)) {
            this["inbox_score"] = 0;
        }
        if (!("inbox_rate" in $$source)) {
            this["inbox_rate"] = 0;
        }
        if (!("inbox_label" in $$source)) {
            this["inbox_label"] = "";
        }
        if (!("spam_test_id" in $$source)) {
            this["spam_test_id"] = "";
        }
        if (!("spam_checked_at" in $$source)) {
            this["spam_checked_at"] = "";
        }
        if (!("spam_summary" in $$source)) {
            this["spam_summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SMTP instance from a string or object.
     */
    static createFrom($$source: any = {}): SMTP {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SMTP($$parsedSource as Partial<SMTP>);
    }
}

export class SMTPStat {
    "id": number;
    "host": string;
    "status": string;
    "sent_count": number;
    "fail_count": number;
    "last_error": string;
    "inbox_label": string;
    "inbox_score": number;
    "inbox_rate": number;

    /** Creates a new SMTPStat instance. */
    constructor($$source: Partial<SMTPStat> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("sent_count" in $$source)) {
            this["sent_count"] = 0;
        }
        if (!("fail_count" in $$source)) {
            this["fail_count"] = 0;
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }
        if (!("inbox_label" in $$source)) {
            this["inbox_label"] = "";
        }
        if (!("inbox_score" in $$source)) {
            this["inbox_score"] = 0;
        }
        if (!("inbox_rate" in $$source)) {
            this["inbox_rate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SMTPStat instance from a string or object.
     */
    static createFrom($$source: any = {}): SMTPStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SMTPStat($$parsedSource as Partial<SMTPStat>);
    }
}

export class StatusCounts {
    "pending": number;
    "sending": number;
    "sent": number;
    "failed": number;
    "smtps_active": number;
    "smtps_disabled": number;

    /** Creates a new StatusCounts instance. */
    constructor($$source: Partial<StatusCounts> = {}) {
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("sending" in $$source)) {
            this["sending"] = 0;
        }
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("smtps_active" in $$source)) {
            this["smtps_active"] = 0;
        }
        if (!("smtps_disabled" in $$source)) {
            this["smtps_disabled"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusCounts instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusCounts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusCounts($$parsedSource as Partial<StatusCounts>);
    }
}

// Private type creation functions
const $$createType0 = Email.createFrom;
const $$createType1 = $Create.Array($$createType0);
