// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inboxcheck$0 from "../inboxcheck/models.js";

export class Config {
    "database": string;
    "workers": number;
    "smtp_max_conn": number;
    "dial_timeout_sec": number;
    "send_timeout_sec": number;
    "retry_max": number;
    "retry_backoff_sec": number;
    "smtp_disable_after_fails": number;
    "batch_commit": number;
    "from_name": string;
    "rate_per_smtp_per_min": number;
    "inbox_check": InboxCheckConfig;
    "shortener": ShortenerConfig;
    "paths": Paths;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("workers" in $$source)) {
            this["workers"] = 0;
        }
        if (!("smtp_max_conn" in $$source)) {
            this["smtp_max_conn"] = 0;
        }
        if (!("dial_timeout_sec" in $$source)) {
            this["dial_timeout_sec"] = 0;
        }
        if (!("send_timeout_sec" in $$source)) {
            this["send_timeout_sec"] = 0;
        }
        if (!("retry_max" in $$source)) {
            this["retry_max"] = 0;
        }
        if (!("retry_backoff_sec" in $$source)) {
            this["retry_backoff_sec"] = 0;
        }
        if (!("smtp_disable_after_fails" in $$source)) {
            this["smtp_disable_after_fails"] = 0;
        }
        if (!("batch_commit" in $$source)) {
            this["batch_commit"] = 0;
        }
        if (!("from_name" in $$source)) {
            this["from_name"] = "";
        }
        if (!("rate_per_smtp_per_min" in $$source)) {
            this["rate_per_smtp_per_min"] = 0;
        }
        if (!("inbox_check" in $$source)) {
            this["inbox_check"] = (new InboxCheckConfig());
        }
        if (!("shortener" in $$source)) {
            this["shortener"] = (new ShortenerConfig());
        }
        if (!("paths" in $$source)) {
            this["paths"] = (new Paths());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inbox_check" in $$parsedSource) {
            $$parsedSource["inbox_check"] = $$createField11_0($$parsedSource["inbox_check"]);
        }
        if ("shortener" in $$parsedSource) {
            $$parsedSource["shortener"] = $$createField12_0($$parsedSource["shortener"]);
        }
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField13_0($$parsedSource["paths"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class InboxCheckConfig {
    "headless": boolean;
    "wait_sec": number;
    "timeout_sec": number;
    "seeds": inboxcheck$0.Seed[];

    /** Creates a new InboxCheckConfig instance. */
    constructor($$source: Partial<InboxCheckConfig> = {}) {
        if (!("headless" in $$source)) {
            this["headless"] = false;
        }
        if (!("wait_sec" in $$source)) {
            this["wait_sec"] = 0;
        }
        if (!("timeout_sec" in $$source)) {
            this["timeout_sec"] = 0;
        }
        if (!("seeds" in $$source)) {
            this["seeds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InboxCheckConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): InboxCheckConfig {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("seeds" in $$parsedSource) {
            $$parsedSource["seeds"] = $$createField3_0($$parsedSource["seeds"]);
        }
        return new InboxCheckConfig($$parsedSource as Partial<InboxCheckConfig>);
    }
}

export class Paths {
    "smtps": string;
    "emails": string;
    "subjects": string;
    "links": string;
    "html": string;

    /** Creates a new Paths instance. */
    constructor($$source: Partial<Paths> = {}) {
        if (!("smtps" in $$source)) {
            this["smtps"] = "";
        }
        if (!("emails" in $$source)) {
            this["emails"] = "";
        }
        if (!("subjects" in $$source)) {
            this["subjects"] = "";
        }
        if (!("links" in $$source)) {
            this["links"] = "";
        }
        if (!("html" in $$source)) {
            this["html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Paths instance from a string or object.
     */
    static createFrom($$source: any = {}): Paths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Paths($$parsedSource as Partial<Paths>);
    }
}

/**
 * ShortenerConfig controls abre.ai link rotation during campaigns.
 */
export class ShortenerConfig {
    "enabled": boolean;

    /**
     * refresh pool after N successful sends
     */
    "every_n": number;

    /**
     * shorts to generate per refresh
     */
    "batch_size": number;

    /**
     * parallel abre.ai calls
     */
    "concurrency": number;

    /** Creates a new ShortenerConfig instance. */
    constructor($$source: Partial<ShortenerConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("every_n" in $$source)) {
            this["every_n"] = 0;
        }
        if (!("batch_size" in $$source)) {
            this["batch_size"] = 0;
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortenerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ShortenerConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortenerConfig($$parsedSource as Partial<ShortenerConfig>);
    }
}

// Private type creation functions
const $$createType0 = InboxCheckConfig.createFrom;
const $$createType1 = ShortenerConfig.createFrom;
const $$createType2 = Paths.createFrom;
const $$createType3 = inboxcheck$0.Seed.createFrom;
const $$createType4 = $Create.Array($$createType3);
