// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RatePoint {
    "t": number;
    "rate": number;
    "sent": number;

    /** Creates a new RatePoint instance. */
    constructor($$source: Partial<RatePoint> = {}) {
        if (!("t" in $$source)) {
            this["t"] = 0;
        }
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RatePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): RatePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RatePoint($$parsedSource as Partial<RatePoint>);
    }
}
