// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes engine methods to the React frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./internal/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inboxcheck$0 from "./internal/inboxcheck/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function AnalyzeAllSmtps(): $CancellablePromise<engine$0.AnalyzeAllResult> {
    return $Call.ByID(1020526634).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AnalyzeSmtp(id: number): $CancellablePromise<inboxcheck$0.PlacementSummary> {
    return $Call.ByID(403028374, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClearErrorLogs(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(895199944).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteAllEmails(): $CancellablePromise<number> {
    return $Call.ByID(1343239309);
}

export function ExtractAllSmtpContacts(): $CancellablePromise<{ [_ in string]?: engine$0.ExtractMailboxResult }> {
    return $Call.ByID(4184004127).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ExtractSmtpContacts(id: number): $CancellablePromise<engine$0.ExtractMailboxResult> {
    return $Call.ByID(3072189558, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(3902498144).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetHtml(): $CancellablePromise<string> {
    return $Call.ByID(1006639387);
}

export function GetLinks(): $CancellablePromise<string[]> {
    return $Call.ByID(2768139127).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetStats(): $CancellablePromise<engine$0.Stats> {
    return $Call.ByID(633111325).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetStatus(): $CancellablePromise<store$0.StatusCounts> {
    return $Call.ByID(3451113224).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetSubjects(): $CancellablePromise<string[]> {
    return $Call.ByID(1671728571).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ImportAll(): $CancellablePromise<{ [_ in string]?: engine$0.ImportResult }> {
    return $Call.ByID(1225466290).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ImportEmailsFile(path: string, validate: boolean): $CancellablePromise<engine$0.ImportResult> {
    return $Call.ByID(3905391460, path, validate).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ImportEmailsText(raw: string, validate: boolean): $CancellablePromise<engine$0.ImportResult> {
    return $Call.ByID(1961058889, raw, validate).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ImportLinksText(raw: string): $CancellablePromise<engine$0.ImportResult> {
    return $Call.ByID(1407052815, raw).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ImportSmtpsText(raw: string): $CancellablePromise<engine$0.ImportResult> {
    return $Call.ByID(1547369475, raw).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ImportSubjectsText(raw: string): $CancellablePromise<engine$0.ImportResult> {
    return $Call.ByID(3114451417, raw).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListEmails(filter: string, limit: number, offset: number): $CancellablePromise<store$0.Email[]> {
    return $Call.ByID(3367881907, filter, limit, offset).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListEmailsPage(filter: string, query: string, limit: number, offset: number): $CancellablePromise<store$0.EmailPage> {
    return $Call.ByID(3131950888, filter, query, limit, offset).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListSmtps(): $CancellablePromise<store$0.SMTP[]> {
    return $Call.ByID(2265968851).then(($result: any) => {
        return $$createType15($result);
    });
}

export function PauseCampaign(): $CancellablePromise<void> {
    return $Call.ByID(626505470);
}

export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(256856770);
}

export function ReenableSMTPs(): $CancellablePromise<number> {
    return $Call.ByID(1658253921);
}

export function ResetFailed(): $CancellablePromise<number> {
    return $Call.ByID(1611709404);
}

export function ResumeCampaign(): $CancellablePromise<void> {
    return $Call.ByID(1792002323);
}

export function SaveConfig(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(2775748437, cfg);
}

export function SetHtml(html: string): $CancellablePromise<void> {
    return $Call.ByID(2229990455, html);
}

export function SetSmtpActive(id: number, active: boolean): $CancellablePromise<void> {
    return $Call.ByID(627473504, id, active);
}

export function StartCampaign(): $CancellablePromise<void> {
    return $Call.ByID(607099760);
}

export function TestSmtp(id: number, to: string): $CancellablePromise<void> {
    return $Call.ByID(209571446, id, to);
}

// Private type creation functions
const $$createType0 = engine$0.AnalyzeAllResult.createFrom;
const $$createType1 = inboxcheck$0.PlacementSummary.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = engine$0.ExtractMailboxResult.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = config$0.Config.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = engine$0.Stats.createFrom;
const $$createType8 = store$0.StatusCounts.createFrom;
const $$createType9 = engine$0.ImportResult.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = store$0.Email.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = store$0.EmailPage.createFrom;
const $$createType14 = store$0.SMTP.createFrom;
const $$createType15 = $Create.Array($$createType14);
